# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/c8813q/setup-makefiles.sh


PRODUCT_COPY_FILES += \
    vendor/huawei/c8813q/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/huawei/c8813q/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/huawei/c8813q/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/huawei/c8813q/proprietary/bin/gps_check:system/bin/gps_check \
    vendor/huawei/c8813q/proprietary/bin/load_oemlogo:system/bin/load_oemlogo \
    vendor/huawei/c8813q/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/huawei/c8813q/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/huawei/c8813q/proprietary/bin/modempre:system/bin/modempre \
    vendor/huawei/c8813q/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/huawei/c8813q/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/huawei/c8813q/proprietary/bin/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/huawei/c8813q/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/huawei/c8813q/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/c8813q/proprietary/bin/rmt_oeminfo:system/bin/rmt_oeminfo \
    vendor/huawei/c8813q/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/huawei/c8813q/proprietary/bin/thermald:system/bin/thermald \
    vendor/huawei/c8813q/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
	vendor/huawei/c8813q/proprietary/bin/hciattach:system/bin/hciattach \
	vendor/huawei/c8813q/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/huawei/c8813q/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/huawei/c8813q/proprietary/lib/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \
    vendor/huawei/c8813q/proprietary/lib/libchromatix_ov5647_ff_default_video.so:system/lib/libchromatix_ov5647_ff_default_video.so \
    vendor/huawei/c8813q/proprietary/lib/libchromatix_ov5647_ff_preview.so:system/lib/libchromatix_ov5647_ff_preview.so \
    vendor/huawei/c8813q/proprietary/lib/libchromatix_ov5647_ff_video_hfr.so:system/lib/libchromatix_ov5647_ff_video_hfr.so \
    vendor/huawei/c8813q/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
    vendor/huawei/c8813q/proprietary/lib/libchromatix_ov5647_video_hfr.so:system/lib/libchromatix_ov5647_video_hfr.so \
    vendor/huawei/c8813q/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/huawei/c8813q/proprietary/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
    vendor/huawei/c8813q/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
    vendor/huawei/c8813q/proprietary/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
    vendor/huawei/c8813q/proprietary/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
    vendor/huawei/c8813q/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/huawei/c8813q/proprietary/lib/libcommon_time_client.so:system/lib/libcommon_time_client.so \
    vendor/huawei/c8813q/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/c8813q/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/huawei/c8813q/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/huawei/c8813q/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/c8813q/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/huawei/c8813q/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/huawei/c8813q/proprietary/lib/libdsucsd.so:system/lib/libdsucsd.so \
    vendor/huawei/c8813q/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/huawei/c8813q/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/huawei/c8813q/proprietary/lib/libgetzip.so:system/lib/libgetzip.so \
    vendor/huawei/c8813q/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/c8813q/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/c8813q/proprietary/lib/libhwnv.so:system/lib/libhwnv.so \
    vendor/huawei/c8813q/proprietary/lib/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/c8813q/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/huawei/c8813q/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/huawei/c8813q/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/huawei/c8813q/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/huawei/c8813q/proprietary/lib/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/huawei/c8813q/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/huawei/c8813q/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/huawei/c8813q/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/huawei/c8813q/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/huawei/c8813q/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/huawei/c8813q/proprietary/lib/libmm-audio-resampler.so:system/lib/libmm-audio-resampler.so \
    vendor/huawei/c8813q/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/huawei/c8813q/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/huawei/c8813q/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/huawei/c8813q/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/huawei/c8813q/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/huawei/c8813q/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/huawei/c8813q/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/huawei/c8813q/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/c8813q/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/c8813q/proprietary/lib/libmmirunning.so:system/lib/libmmirunning.so \
    vendor/huawei/c8813q/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/c8813q/proprietary/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so \
    vendor/huawei/c8813q/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/huawei/c8813q/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/huawei/c8813q/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/huawei/c8813q/proprietary/lib/libmvs.so:system/lib/libmvs.so \
    vendor/huawei/c8813q/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/huawei/c8813q/proprietary/lib/libnl_2.so:system/lib/libnl_2.so \
    vendor/huawei/c8813q/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/c8813q/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/c8813q/proprietary/lib/liboeminfo.so:system/lib/liboeminfo.so \
    vendor/huawei/c8813q/proprietary/lib/liboeminfodata.so:system/lib/liboeminfodata.so \
    vendor/huawei/c8813q/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxAc3HwDec.so:system/lib/libOmxAc3HwDec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxIttiamVenc.so:system/lib/libOmxIttiamVenc.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/huawei/c8813q/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/huawei/c8813q/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/c8813q/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/c8813q/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/huawei/c8813q/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/huawei/c8813q/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/huawei/c8813q/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/huawei/c8813q/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/c8813q/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/huawei/c8813q/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
    vendor/huawei/c8813q/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/huawei/c8813q/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/c8813q/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/huawei/c8813q/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/c8813q/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/huawei/c8813q/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/c8813q/proprietary/lib/libshareril.so:system/lib/libshareril.so \
    vendor/huawei/c8813q/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/huawei/c8813q/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/c8813q/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/huawei/c8813q/proprietary/lib/libzy_imgdenoise.so:system/lib/libzy_imgdenoise.so \
    vendor/huawei/c8813q/proprietary/lib/hw/camera.msm7x27a.so:system/lib/hw/camera.msm7x27a.so \
    vendor/huawei/c8813q/proprietary/lib/hw/lights.msm7x27a.so:system/lib/hw/lights.msm7x27a.so \
    vendor/huawei/c8813q/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/huawei/c8813q/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/huawei/c8813q/proprietary/lib/libcontrast.so:system/lib/libcontrast.so \
    vendor/huawei/c8813q/proprietary/lib/libadc.so:system/lib/libadc.so \
    vendor/huawei/c8813q/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/huawei/c8813q/proprietary/bin/rild:system/bin/rild \
    vendor/huawei/c8813q/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/huawei/c8813q/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/huawei/c8813q/proprietary/lib/libaudcal.so:obj/lib/libaudcal.so
